---
title: "label_genes"
author: "Jared Bard"
date: "4/29/2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
`%!in%` = Negate(`%in%`)
```
#Create a labeled list of genes
Annotate genes based on a combination of David pincus's list of hsf1 targets, Soli MSN2/4 Cat's transcription factor lists, Allan's lists, and a couple other databases
```{r}
genes_scer <- read_tsv("200325-scer-features.txt",comment="#")%>%select(ORF,gene,length.prot,classification)
pincus_mbc_targets <- c("YGR142W", "YBR101C", "YOR027W", "YPL240C", "YMR186W", "YLL024C", "YNL064C", "YDR214W", "YLR216C", "YNL007C", "YAL005C", "YPR158W", "YDR258C", "YFL016C", "YNL281W", "YDR171W", "YLL026W", "YOR298C-A", "YER103W", "YGR211W", "YNL077W", "YPL250C", "YBR072W", "YPL106C", "YOL081W", "YNR069C", "YCR021C", "YLR327C", "YLR259C", "YBR169C", "YGR250C", "YPR154W", "YHR082C", "YOR020C", "YCL050C", "YDL020C", "YJR045C", "YJL034W", "YHR104W", "YGR161C", "YBR067C", "YDR151C", "YBR025C", "YBR082C", "YDR011W", "YER150W", "YLL039C", "YOR267C")

solis_data <- read_excel("Solis_2016/mmc3.xlsx", skip = 3, col_types = c(rep("text", 2), rep("numeric", 9), "text"),
                         na="NA")
solis_msn <- filter(solis_data, Gene_Type == "Msn24")$locus

rib <- read_tsv("scer-ribosomal-proteins.txt", comment='#',show_col_types = F)
#glyc <- read_tsv("../src/scer-glycolytic-proteins.txt", comment='#')
sgd_glyc <- read_tsv("SGD_superpathway_glycolysis_221025.txt",skip=2,show_col_types = F) %>%
  rename("ORF"="Gene ID")
ribi <- read_tsv("ribosome_biogenesis_annotations_sgd.txt", comment='#',show_col_types = F)
translation_factors <- read_tsv("translation_factors_kegg.tsv",show_col_types = F)

labeled_genes_scer <- genes_scer %>%
  mutate(label = case_when(
    ORF%in%pincus_mbc_targets~"HSF1",
    ORF%in%rib$orf~"translation",
    ORF%in%ribi$ORF~"translation",
    ORF%in%translation_factors$ORF~"translation",
    ORF%in%sgd_glyc$ORF~"glycolysis",
    ORF%in%solis_msn~"MSN2/4",
    TRUE~"other"))
write_tsv(labeled_genes_scer,"230215_labeled_genes_scer.tsv")
```

